name: Cleanup Published Invites

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minute
  workflow_dispatch:  # Manual trigger from GitHub Actions tab

jobs:
  cleanup_job:
    runs-on: ubuntu-latest

    steps:
      - name: Call Cleanup Endpoint
        run: |
          curl -X GET https://wedding-invite-backend-r0zm.onrender.com/cleanup
